CREATE TABLE USER_DB(
    ID BIGINT NOT NULL,
    MAIL VARCHAR(40),
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(20),
    QUESTION_STATUS INT,
    QUESTION_COUNT INT,
    ANSWER_COUNT INT,
    DATE DATE
);
ALTER TABLE PUBLIC.USER_DB ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

CREATE SEQUENCE PUBLIC.USER_SEQUENCE START WITH 100;

CREATE TABLE QUESTION_DB(
    ID BIGINT NOT NULL,
    TITLE VARCHAR(40),
    CONTENT VARCHAR(20),
    LIKE_COUNT INT,
    DISLIKE_COUNT INT,
    DATE DATE,
    USER_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.QUESTION_DB ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);

CREATE SEQUENCE PUBLIC.QUESTION_SEQ START WITH 100;

CREATE TABLE ANSWER_DB(
    ID BIGINT NOT NULL,
    CONTENT VARCHAR(20),
    LIKE_COUNT INT,
    DISLIKE_COUNT INT,
    QUESTION_ID BIGINT,
    VERIFIED BIT ,
    OWNER_ID BIGINT,
    USER_ID BIGINT,
    DATE DATE
);
ALTER TABLE PUBLIC.ANSWER_DB ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);

CREATE SEQUENCE PUBLIC.ANSWER_SEQ START WITH 100;