CREATE TABLE USER_DB(
    ID BIGINT NOT NULL,
    MAIL VARCHAR(40),
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(20),
    QUESTION_STATUS INT,
    DATE DATE
);
ALTER TABLE PUBLIC.USER_DB ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

CREATE SEQUENCE PUBLIC.USER_SEQUENCE START WITH 100;